import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import ChartSidebar from "@/components/ChartSidebar";
import RightSidebar from "@/components/RightSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <div className="flex ">
          <div>
            <Sidebar />
          </div>
          <div className="w-full flex">
            <ChartSidebar />
            <div className="w-full bg-gradient-to-t from-[#E8E8F2] to-[#F4D5D3]">
              <Header />
              {children}
            </div>
          </div>
        </div> */}
        <div className="flex ">
          <div>
            <Sidebar />
          </div>
          <div className="w-full  bg-gradient-to-t from-[#E8E8F2] to-[#F4D5D3]">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
